name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test_linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up node.js 20.11
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  build_and_test_windows:
  
      runs-on: windows-latest
  
      steps:
      - uses: actions/checkout@v4
      - name: Set up node.js 20.11
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
  