name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test_linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: erlef/setup-beam@v1
      with:
        otp-version: '27'
        elixir-version: '1.17.2'
    - run: mix archive.install hex phx_new --force
    - run: mix phx.new demo --install
    - run: ls
    - name: Set up node.js 20.11
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  build_and_test_windows:
  
      runs-on: windows-latest
  
      steps:
      - uses: actions/checkout@v4
      - name: setup-beam
        uses: erlef/setup-beam@v1.18.1
        with:
          otp-version: '27'
          elixir-version: '1.17.2'
      - run: mix archive.install hex phx_new
      - name: Set up node.js 20.11
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
  
